eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8030/eureka
  instance:
    hostname: localhost
zuul:
  prefix: /api
  routes:
    productCatalogService:
      path: /productCatalogService/**
      url: http://localhost:8070
    pricingService:
      path: /pricingService/**
      url: http://localhost:8072